# Planetscale uses mysql `8.0.23-Vitess` which is not available as a container
# PS sql_mode = ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
# But the `STRICT_TRANS_TABLES` causes an error when initializing the db. So it has been removed.
# https://mariadb.com/docs/skysql-dbaas/ref/es23.07/sql-modes/

# Usage
# docker compose up -d
# DATABASE_URL="mysql://root:root@localhost/track-the-hack"
# npx prisma db push

services:
    track-the-hack-db:
        image: mysql
        restart: always
        command: --sql_mode="ONLY_FULL_GROUP_BY,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
        environment:
            - MYSQL_ROOT_PASSWORD=root
        ports:
            - 3306:3306
        volumes:
            - mysql_data:/var/lib/mysql

volumes:
    mysql_data:
        driver: local
