import { useSession } from "next-auth/react";
import Head from "next/head";

import Navbar from "../components/Menu";

const App = ({ children }: { children: React.ReactNode }) => {
	const { data: sessionData } = useSession();

	return (
		<>
			<Head>
				<title>Track the Hack</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Navbar />
			<main className="p-4">
				<p>{sessionData && <span>Logged in as {sessionData.user?.name}</span>}</p>
				<br />
				{children}
			</main>
		</>
	);
};

export default App;
