ALTER TABLE `Event` DROP COLUMN `tiktok`;

ALTER TABLE `PushSubscription`
    ADD COLUMN `locale` VARCHAR(2) NOT NULL DEFAULT 'en',
    MODIFY `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);

ALTER TABLE `EventInterest`
    MODIFY `hackerId` VARCHAR(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL;
