import type { ArchiveDashboard } from "@root/private-metrics/snapshot";
export const privateMetricsFixture: ArchiveDashboard = {
	formatVersion: 1,
	capturedAt: "2026-10-01T12:00:00.000Z",
	metrics: {
		provisioned: 10,
		confirmed: 8,
		walkIn: 2,
		checkedIn: 7,
		presences: 12,
		attendanceOutcomes: {
			confirmedAttended: 5,
			confirmedAbsent: 3,
			attendedWithoutConfirmation: 2,
			attendedWalkIns: 1,
		},
		rsvp: { confirmed: 8, declined: 1, pending: 1 },
		attendanceData: [{ eventId: "fixture-event", label: "Check-in", uniqueParticipants: 7, recordedUnits: 7 }],
		engagementData: [
			{ key: "none", participants: 3 },
			{ key: "one", participants: 7 },
		],
		mealCategoryData: [],
		tShirtSizeData: [],
		attendanceIntegrity: {
			issuedPassesWithoutCheckIn: 0,
			positivePresenceWithoutCheckIn: 0,
			visibleCheckInEvents: 1,
		},
		funnel: {
			applications: 20,
			accepted: 10,
			acceptanceEmailsSesAccepted: 11,
			confirmed: 8,
			checkedIn: 7,
			devpostProjects: 4,
			devpostRegistrants: 9,
			devpostActiveRegistrants: 8,
			devpostSubmitters: 7,
			devpostSubmittedProjects: 5,
			devpostPublicProjects: 4,
		},
		conversions: {
			participation: {
				applicationToAccepted: { from: 20, to: 10, dropOff: 10, rate: 50 },
				acceptedToConfirmed: { from: 10, to: 6, dropOff: 4, rate: 60 },
				confirmedToAttended: { from: 8, to: 5, dropOff: 3, rate: 62.5 },
			},
			devpost: {
				registrantToActive: { from: 9, to: 8, dropOff: 1, rate: 88.9 },
				activeToSubmitter: { from: 8, to: 7, dropOff: 1, rate: 87.5 },
				submittedToPublicProject: { from: 5, to: 4, dropOff: 1, rate: 80 },
				publicToJudgingProject: { from: 4, to: 4, dropOff: 0, rate: 100 },
			},
		},
		dataQuality: {
			sheetRows: 20,
			sheetLinkedRows: 10,
			sheetUnlinkedRows: 10,
			duplicateApplicationRows: 1,
			devpostMatchedRegistrants: 6,
			devpostUnmatchedRegistrants: 3,
			devpostMatchedSubmitters: 4,
			devpostProjectImportGap: 0,
		},
		externalMetrics: {
			sheet: {
				capturedAt: "2026-09-29T12:00:00.000Z",
				payload: {
					kind: "google-sheets",
					rows: 20,
					linkedRows: 10,
					cohorts: { applicants: 20, accepted: 10, confirmed: 6, attended: 7 },
					dimensions: {
						school: [
							{ label: "Fixture school", applicants: 10, accepted: 5, confirmed: 3, attended: 4 },
							{ label: "Other / suppressed", applicants: 10, accepted: 5, confirmed: 3, attended: 3 },
						],
					},
				},
			},
			communications: {
				capturedAt: "2026-09-29T13:00:00.000Z",
				payload: { kind: "communications", acceptanceEmailsSesAccepted: 11 },
			},
			devpost: {
				capturedAt: "2026-09-29T14:00:00.000Z",
				payload: {
					kind: "devpost",
					registrants: 9,
					activeRegistrants: 8,
					submitters: 7,
					submittedProjects: 5,
					publicProjects: 4,
					hiddenProjects: 1,
					draftProjects: 2,
					teamUpRequests: 1,
					linkage: {
						applicationRows: 20,
						uniqueApplicationEmails: 19,
						duplicateApplicationRows: 1,
						matchedRegistrants: 6,
						matchedAccepted: 5,
						matchedConfirmed: 4,
						matchedAttended: 3,
						matchedSubmitters: 4,
						matchedAcceptedSubmitters: 4,
						matchedConfirmedSubmitters: 3,
						matchedAttendedSubmitters: 2,
						unmatchedRegistrants: 3,
					},
				},
			},
		},
	},
};
