name: Node.js CI

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        runs-on: self-hosted
        environment: Production
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Use Node.js 20.x
              uses: actions/setup-node@v3
              with:
                  node-version: 20.x
                  cache: "npm"

            - name: Cache Next.js build
              uses: actions/cache@v3
              with:
                  path: /home/azure/track-the-hack/.next/cache
                  key: ${{ runner.os }}-nextjs-${{ hashFiles('/home/azure/track-the-hack/package-lock.json') }}-${{ hashFiles('/home/azure/track-the-hack/**.[jt]s', '/home/azure/track-the-hack/**.[jt]sx') }}
                  restore-keys: |
                      ${{ runner.os }}-nextjs-${{ hashFiles('/home/azure/track-the-hack/package-lock.json') }}-

            - name: Deploy to production directory
              run: rsync -avz --delete ./ /home/azure/track-the-hack/

            - name: Install dependencies
              working-directory: /home/azure/track-the-hack
              run: npm ci

            - name: Create .env file
              working-directory: /home/azure/track-the-hack
              run: node ./.github/workflows/create-env.mjs "$SECRETS"
              env:
                  SECRETS: ${{ toJson(secrets) }}

            - name: Build
              working-directory: /home/azure/track-the-hack
              run: npm run build --if-present

            - name: Update the database schema
              working-directory: /home/azure/track-the-hack
              run: npx prisma migrate deploy

            - name: Restart the server
              working-directory: /home/azure/track-the-hack
              run: pm2 restart track-the-hack && pm2 restart prisma
