name: Node.js CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: self-hosted
    environment: Production
    env:
      WORKING_DIRECTORY: /home/azure/track-the-hack
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: ${{ env.WORKING_DIRECTORY }}

      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "npm"
          cache-dependency-path: ${{ env.WORKING_DIRECTORY }}/package-lock.json

      - name: Cache Next.js build
        uses: actions/cache@v3
        with:
          path: ${{ env.WORKING_DIRECTORY }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('${{ env.WORKING_DIRECTORY }}/package-lock.json') }}-${{ hashFiles('${{ env.WORKING_DIRECTORY }}/**.[jt]s', '${{ env.WORKING_DIRECTORY }}/**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('${{ env.WORKING_DIRECTORY }}/package-lock.json') }}-

      - name: Install dependencies
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: npm ci

      - name: Create .env file
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: node ./.github/workflows/create-env.mjs "$SECRETS"
        env:
          SECRETS: ${{ toJson(secrets) }}

      - name: Build
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: npm run build --if-present

      - name: Restart the server
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: pm2 restart track-the-hack
